from app.llm import create_llm


def main():
    # executes create_llm() and the resulting object is stored in the variable
    llm = create_llm()

    # sends the message to the model and awaits its response
    response = llm.invoke(
        "Explica brevemente qué es una garantía de producto."
    )

    print("Respuesta del modelo:\n")
    # gets only the text generated by the model
    print(response.content)


if __name__ == "__main__":
    main()